### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by jregalad** [algbioi/snowball#4]
snowball crashed:

**COMMAND LINE:**
    snowball -f R1-trimmed.fq -s R2-trimmed.fq -m Pfam-A.hmm -i 225 -r 140 -p 15

**STDOUT**
This hmmsearch binary will be used:
"path to hmmsearch"
Using temporary directory:
/tmp/snowball_FRFjf1
Running on: Ubuntu 14.04 trusty (linux2)
Using 15 processors
Settings:
Read length: 140
Insert size: 225
Min. overlap probability: 0.8
Min. overlap length: 0.5
Min. HMM score: 40
Joining paired-end reads into consensus reads, loading reads from:
"path"R1-trimmed.fq
"path"R2-trimmed.fq
Filtered out: 99.259 % reads
Translating reads to protein sequences
Running HMMER (hmmsearch)
Assigning consensus reads to gene domains
Exception in partitionReads:
/tmp/snowball_FRFjf1 40 0.6 1 sample_partitioned True
Not a gzipped file
<type 'exceptions.IOError'>
('Not a gzipped file',)
Traceback (most recent call last):
File "/ebio/abt6_projects9/microbiome_analysis/data/software/mypython/envs/snowball/bin/snowball", line 493, in <module>
_main()
File "/ebio/abt6_projects9/microbiome_analysis/data/software/mypython/envs/snowball/bin/snowball", line 468, in _main
outAnnot=outAnnot, cleanUp=cleanUp, processors=processors)
File "/ebio/abt6_projects9/microbiome_analysis/data/software/mypython/envs/snowball/bin/snowball", line 199, in mainSnowball
comh.SAMPLES_SHUFFLE_RAND_SEED, comh.SAMPLES_PFAM_PARTITIONED_DIR, True, False)
File "/ebio/abt6_projects9/microbiome_analysis/data/software/mypython/envs/snowball/bin/algbioi/haplo/hio.py", line 423, in partitionReads
raise e
IOError: Not a gzipped file

Did I provide a file that was expected to be gzipped but was uncompressed?

**Comment by algbioi** [comment]
The problem is that the input paired-end reads are not sufficiently self-overlapping, as 99.259% reads were filtered out because of that. Unfortunately, it looks like your input data doesn't contain sufficiently self-overlapping paired-end reads and therefore Snowball is not suitable to analyse them.
